### ISSUE TITLE
Deal with missing permissions; add console logging

### ISSUE THREAD

**Issue by cbacon91** [cbacon91/DiscordNameGen#18]
`(node:16052) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): DiscordAPIError: Missing Permissions
(node:16052) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

This happened overnight-  not sure what happened? was the bot missing permissions to send / read messages?

**Comment by cbacon91** [comment]
Not sure if this is an exact replication, BUT...

If you add the bot to a server with 'read messages' but without 'send messages' permission, it blows up. I assume this happens on servers where the owner either strips away permissions or the server has strong security (must be on for 5 minutes, etc).

Should change this logic internally to something like ...

```
if ( cannot send message)
  reply to person who asked for command with "I don't have enough permissions, either wait a bit if the server has high security or give me the 'send messages' permission"
```

**Comment by Gyzimo** [comment]
If a server has a high lvl security this should only effect user accounts not bot accounts. 
You can fix this issue in either 2 ways.  You could put your code that requires these permissions within a 

`try {
} catch (err) {
return; 
}`

This will try the code and if an error occurs it just returns. 
I just do return as this an issue you can not fix due to the server
changing it permissions. You can also choose at the return to DM
the server owner about the faulty permissions or letting the bot 
simply leave the server.  I personally do this if they took the 
SEND_MESSAGES away from it.  very annoying. 

You can also just let the bot search for the permissions 
before executing the rest of the code.
